Add nfs4 support to ws_share

diff --git a/bin/ws_share b/bin/ws_share
--- a/bin/ws_share
+++ b/bin/ws_share
@@ -18,7 +18,7 @@
 #          (c) Holger Berger 2026
 #
 
-progname=$(basename $0)
+progname="$(basename $0)"
 maxmembers=100 # do not share with a group with more than $maxmembers members
 
 # Test for compatible getopt version.
@@ -75,6 +75,7 @@ unset PARSED
 
 YES="NO"
 ACCESS="rX"  # default: read-only
+NFS4_ACCESS="RX"  # default: read-only
 # parse options
 while true; do
     case "$1" in
@@ -92,6 +93,7 @@ while true; do
             ;;
         --readwrite)
             ACCESS="rwX"
+            NFS4_ACCESS="RWX"
             shift
             ;;
 	--yes)
@@ -134,17 +136,28 @@ if [[ $? -ne 0 || -z "$WS_PATH" ]]; then
     exit 1
 fi
 
+get_mount_point() {
+    local file_path="$1"
+    df -P "$file_path" | awk 'NR==2 {print $6}'
+}
+# Determine which file system
+MOUNTPOINT=$(get_mount_point "$WS_PATH")
+# Determine if it's using nfs4
+# equivalent to:  pcregrep -o1 " $MOUNTPOINT .*vers=(.)" /proc/mounts
+NFS_VERS=$(grep " $MOUNTPOINT nfs.*vers=" /proc/mounts | sed -E 's/.*vers=(.).*/\1/')
+USE_NFS4=0
+if [ -n "$NFS_VERS" ] && [ "$NFS_VERS" -ge 4 ]; then
+    USE_NFS4=1
+fi
+
 case $ACTION in
     list)
         getfacl -apt "$WS_PATH" | awk '/user|group|USER|GROUP/&&!/---/{gsub("rw.","readwrite");gsub("r-.","read");print}'
         ;;
     share)
         USERS="$@"
-        if [[ -z "$USERS" ]]; then
-            echo "Error: No user specified"
-            exit 1
-        fi
         MACL=""
+        NFS4_ACL=""
         for user in $USERS; do
             if ! id "$user" >/dev/null 2>&1; then
                 echo "Error: User $user unknown"
@@ -153,18 +166,24 @@ case $ACTION in
             echo "Granting $ACCESS access for user $user ..."
             MACL+="user:$user:$ACCESS,"
             MACL+="default:user:$user:$ACCESS,"
+            SHARE_UID=$(id -ru "$user")
+            NFS4_ACL+="A:d:$SHARE_UID:$NFS4_ACCESS,"
         done
         if [[ -z "$MACL" ]]; then
             exit 0
         fi
-        setfacl -R -m "${MACL%,}" "$WS_PATH"
+
+        if [ "$USE_NFS4" == 1 ];  then
+            nfs4_setfacl -R -a "$NFS4_ACL" "$WS_PATH"
+        else
+            setfacl -R -m "${MACL%,}" "$WS_PATH"
+        fi
+        if [ "$?" -eq 0 ]; then
+            echo "Success!"
+        fi
         ;;
     unshare)
         USERS="$@"
-        if [[ -z "$USERS" ]]; then
-            echo "Error: No user specified"
-            exit 1
-        fi
         XACL=""
         for user in $USERS; do
             if ! id "$user" >/dev/null 2>&1; then
@@ -174,11 +193,18 @@ case $ACTION in
             echo "Removing access for $user"
             XACL+="user:$user,"
             XACL+="default:user:$user,"
+            SHARE_UID="$(id -ru $user)"
+            # Ensure we don't match groups with the same UID
+            NFS4_ACL+=$(nfs4_getfacl "$WS_PATH" | grep "^A:[^g]*:$SHARE_UID" | paste -d, -s),
         done
         if [[ -z "$XACL" ]]; then
             exit 0
         fi
-        setfacl -R -x "${XACL%,}" "$WS_PATH"
+        if [ "$USE_NFS4" == 1 ];  then
+            nfs4_setfacl -R -x "$NFS4_ACL" "$WS_PATH"
+        else
+            setfacl -R -x "${XACL%,}" "$WS_PATH"
+        fi
         ;;
     sharegroup)
         GROUPARG="$@"
@@ -200,21 +226,30 @@ case $ACTION in
             echo "Granting $ACCESS access for group $group ..."
             MACL+="group:$group:$ACCESS,"
             MACL+="default:group:$group:$ACCESS,"
+            SHARE_GID=$(getent group "$group" | cut -f3 -d:)
+            NFS4_ACL+="A:dg:$SHARE_GID:$NFS4_ACCESS,"
         done
         if [[ -n "$MACL" ]]; then
           if [[ "$ACCESS" == "rwX" ]] ; then
               echo "Warning: giving write access to your group may:"
               echo "  * allow immediate workspace deletion"
               echo "  * interfere with your quota (depending on system setup)"
-	      if [[ "$YES" != "YES" ]]; then
-		      read -p "Continue (y/N)? " answer
-			case "$answer" in
-			    [yY]*) ;;
-			    *) echo "Aborted."; exit 1 ;;
-			esac
-	      fi
+              if [[ "$YES" != "YES" ]]; then
+                  read -p "Continue (y/N)? " answer
+                case "$answer" in
+                    [yY]*) ;;
+                    *) echo "Aborted."; exit 1 ;;
+                esac
+              fi
           fi
-          setfacl -R -m "${MACL%,}" "$WS_PATH"
+          if [ "$USE_NFS4" == 1 ];  then
+              nfs4_setfacl -R -a "$NFS4_ACL" "$WS_PATH"
+          else
+              setfacl -R -m "${MACL%,}" "$WS_PATH"
+          fi
+          if [ "$?" -eq 0 ]; then
+              echo "Success!"
+          fi
         fi
         ;;
     unsharegroup)
@@ -234,13 +269,34 @@ case $ACTION in
             sleep 3;
             XACL+="group:$group,"
             XACL+="default:group:$group,"
+            SHARE_GID=$(getent group "$group" | cut -f3 -d:)
+            # Ensure we don't match users with the same UID
+            NFS4_ACL+=$(nfs4_getfacl "$WS_PATH" | grep "^A:[^:]*g[^:]*:$SHARE_UID" | paste -d, -s),
         done
-        [[ -n "$XACL" ]] && setfacl -R -x "${XACL%,}" "$WS_PATH"
+        if [ "$USE_NFS4" == 1 ];  then
+            echo "Removing ACLs: $NFS4_ACL"
+            nfs4_setfacl -R -x "$NFS4_ACL" "$WS_PATH"
+        else
+            [[ -n "$XACL" ]] && setfacl -R -x "${XACL%,}" "$WS_PATH"
+        fi
+        if [ "$?" -eq 0 ]; then
+            echo "Success!"
+        fi
         ;;
     unshare-all)
         echo "Warning: will produce errors on files not owned by you"
         sleep 3;
-        setfacl -R -b "$WS_PATH"
+        if [ "$USE_NFS4" == 1 ];  then
+            echo "Removing ACLs:"
+            # Default rules don't have UID numbers
+            nfs4_getfacl -c "$WS_PATH"  |  grep -wEe "[0-9]+"
+            nfs4_getfacl -c "$WS_PATH"  |  grep -wEe "[0-9]+"  |  nfs4_setfacl -R -X - "$WS_PATH"
+        else
+            setfacl -R -b "$WS_PATH"
+        fi
+        if [ "$?" -eq 0 ]; then
+            echo "Success!"
+        fi
         ;;
     check)
         ;;
